add structure option
Former-commit-id: 3fb994b689243c6d25119caca0eaf4d3f3812a3a

diff --git a/scripts/create_masks b/scripts/create_masks
--- a/scripts/create_masks
+++ b/scripts/create_masks
@@ -8,7 +8,7 @@
 
 Usage() {
     echo ""
-    echo "Usage: create_masks [-ref <path>] [-warp <path>] [-out <folder>] [-aparc <path>] [str <str_name>]"
+    echo "Usage: create_masks [-ref <path>] [-warp <path>] [-out <folder>] [-aparc <path>] [-str <str_name>]"
     echo ""
     echo "Example usage: create_masks -ref subj001/t1.nii.gz -out subj001 -aparc subj001/aparc.a2009s+aseg.nii.gz -warp subj001/std2str_warp.nii.gz -str vim"
     echo ""
@@ -62,6 +62,7 @@ warp=""
 aparc=""
 out=""
 brainmask=""
+str=""
 
 ### parse arguments
 while [ -n "$1" ]; do
@@ -87,6 +88,10 @@ while [ -n "$1" ]; do
       ;;
     -brainmask)
       brainmask="$2"
+      shift
+      ;;
+    -str)
+      str="$2"
       shift
       ;;
     *)
@@ -127,6 +132,11 @@ fi
 
 if [ -z "$out" ]; then
   echo "Error: Missing required argument -out. Please specify the output directory."
+  exit 1
+fi
+
+if [ -z "$str" ]; then
+  echo "Error: Missing required argument -str. Please specify the structure to be localised."
   exit 1
 fi
 
