fix short flags
Former-commit-id: 26e565b87fbccdfa05a00f4c0a771df41f772701

diff --git a/scripts/create_masks b/scripts/create_masks
--- a/scripts/create_masks
+++ b/scripts/create_masks
@@ -126,7 +126,9 @@ do
       shift
       ;;
     *)
-    
+      # echo "Error: Invalid argument: $arg"
+      # Usage
+      # exit 1
     ;;
   esac
 done
