rearrange create_masks

diff --git a/scripts/create_masks b/scripts/create_masks
--- a/scripts/create_masks
+++ b/scripts/create_masks
@@ -7,22 +7,29 @@
 # Written by Ying-Qiu Zheng
 
 Usage() {
-    echo ""
-    echo "Usage: create_masks [-ref <path>] [-warp <path>] [-out <folder>] [-aparc <path>] [-str <str_name>]"
-    echo ""
-    echo "Example usage: create_masks -ref subj001/t1.nii.gz -out subj001 -aparc subj001/aparc.a2009s+aseg.nii.gz -warp subj001/std2str_warp.nii.gz -str vim"
-    echo ""
-    echo "Description:"
-    echo "  Creates anatomical masks in reference space (-ref) for tractography and stores them under the output folder."
-    echo ""
-    echo "Options:"
-    echo "  -ref <path>                   Path to reference image, typically in T1 native space or diffusion space."
-    echo "  -warp <path>                  Path to warp field mapping the MNI standard space to the reference space."
-    echo "  -aparc <path>                 Path to cortical segmentation file generated by Freesurfer. Must be inthe reference space."
-    echo "  -out <folder>                 Path to output folder."
-    echo "  -str <strcture_name>          Name of structure, e.g., vim, lgn, etc."
-    echo "  -brainmask <path>             (Optional) Path to binary brain mask in the reference space."
-    echo ""
+    cat << EOF
+
+Usage:
+    create_masks -ref <path> -warp <path> -out <folder> -aparc <path> -str <str_name> [options]
+
+    Compulsory arguments:
+       -ref <path>                      Path to reference image, i.e., the space you want to run localise in
+       -warp <path>                     Path to warp field mapping the MNI standard space to the reference space
+       -out <folder>                    Path to output folder
+       -aparc <path>                    Path to cortical segmentation file generated by Freesurfer (must be in the reference space)
+       -str <strcture_name>             Name of structure, e.g., vim, lgn, etc.
+
+    Optional arguments:
+       -brainmask <path>                Path to binary brain mask in the reference space
+
+Description:
+    Creates anatomical masks in reference space (-ref) for tractography and stores them under the output folder.
+
+Example usage:
+    create_masks -ref subj001/t1.nii.gz -out subj001 -aparc subj001/aparc.a2009s+aseg.nii.gz -warp subj001/std2str_warp.nii.gz -str vim
+This will create necessary masks for localising vim in the reference space (t1.nii.gz).
+
+EOF
     exit 1
 }
 
@@ -33,9 +40,14 @@ if [ -z "$FSLDIR" ]; then
   exit 1
 fi
 
-## path of the script  ### TODO: have a safer way to fetch the resources path
-SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
-RESOURCES_DIR="$(dirname $SCRIPT_DIR)/resources"
+# Get the resources path using the Python function
+RESOURCES_DIR=$(python -c "from localise.utils import get_resources_path; print(get_resources_path())")
+
+# Check if the resources directory exists
+if [ ! -d "$RESOURCES_DIR" ]; then
+    echo "Error: Resources directory not found at $RESOURCES_DIR"
+    exit 1
+fi
 
 ### make file path absolute
 get_abs_file_path() {
@@ -49,7 +61,7 @@ get_abs_file_path() {
         abs_path=$(readlink -f "$file_path")
     else
         echo "Error: realpath and readlink commands are not available."
-        return 1
+        exit 1
     fi
 
     echo "$abs_path"
@@ -102,54 +114,29 @@ while [ -n "$1" ]; do
 done
 
 ### Check if required arguments are provided
-if [ -z "$ref" ]; then
-  echo "Error: Missing required argument -ref. Please specify the reference image."
-  Usage
-  exit 1
-elif [ ! -f $ref ]; then
-  echo "Error: $ref not exist. "
-  exit 1
-else
-  refpath=$(get_abs_file_path "$ref")
-fi
-
-if [ -z "$warp" ]; then
-  echo "Error: Missing required argument -warp. Please specify the warp field mapping the MNI standard space to reference space."
-  exit 1
-elif [ ! -f $warp ]; then
-  echo "Error: $warp not exist. "
-  exit 1
-fi
-
-if [ -z "$aparc" ]; then
-  echo "Error: Missing required argument -aparc. Please specify the cortical parcellation file (generated by recon-all)."
-  exit 1
-elif [ ! -f $aparc ]; then
-  echo "Error: $aparc not exist. "
-  exit 1
-fi
-
-if [ -z "$out" ]; then
-  echo "Error: Missing required argument -out. Please specify the output directory."
-  exit 1
-fi
-
-if [ -z "$str" ]; then
-  echo "Error: Missing required argument -str. Please specify the structure to be localised."
-  exit 1
-fi
-
-### create output directory
-if [ ! -d $out/masks ]; then
-  mkdir -p $out/masks
-fi
-### create dir for left and right hemisphere
-for hemi in left right; do
-  if [ ! -d $out/masks/$hemi ]; then
-    mkdir $out/masks/$hemi
+for arg in ref warp aparc out str; do
+  if [ -z "${!arg}" ]; then
+    echo "Error: Missing required argument -$arg." >&2
+    Usage
+    exit 1
   fi
 done
 
+### Validate file existence
+for file in ref warp aparc; do
+  if [ ! -f "${!file}" ]; then
+    echo "Error: ${!file} does not exist." >&2
+    exit 1
+  fi
+done
+
+### Get absolute path for ref (assuming get_abs_file_path function exists)
+refpath=$(get_abs_file_path "$ref")
+
+### create output directory
+mkdir -p "$out/masks/left" "$out/masks/right"
+
+### create masks
 if [ ! -z "$aparc" ]; then
   aparc_basename=$(basename "$aparc")
   if [[ "$aparc" == *.mgz ]]; then  # TODO: maybe remove this
@@ -168,28 +155,27 @@ if [ ! -z "$aparc" ]; then
     exit 1
   fi
   #### cerebellum
-  echo "$FSLDIR/bin/fslmaths $aparc -thr 6 -uthr 8 -bin $out/masks/left/cerebellum" > $out/create_masks_cmds
-  echo "$FSLDIR/bin/fslmaths $aparc -thr 45 -uthr 47 -bin $out/masks/right/cerebellum" >> $out/create_masks_cmds
-  echo "$FSLDIR/bin/fslmaths $aparc -thr 7 -uthr 7 -bin $out/masks/right/cerebellum_target" >> $out/create_masks_cmds
-  echo "$FSLDIR/bin/fslmaths $aparc -thr 46 -uthr 46 -bin $out/masks/left/cerebellum_target" >> $out/create_masks_cmds
+  echo "$FSLDIR/bin/fslmaths $aparc -thr 6 -uthr 8 -bin $out/masks/left/cerebellum" > "$out/create_masks_cmds"
+  echo "$FSLDIR/bin/fslmaths $aparc -thr 45 -uthr 47 -bin $out/masks/right/cerebellum" >> "$out/create_masks_cmds"
+  echo "$FSLDIR/bin/fslmaths $aparc -thr 7 -uthr 7 -bin $out/masks/right/cerebellum_target" >> "$out/create_masks_cmds"
+  echo "$FSLDIR/bin/fslmaths $aparc -thr 46 -uthr 46 -bin $out/masks/left/cerebellum_target" >> "$out/create_masks_cmds"
   echo "$FSLDIR/bin/fslmaths $aparc -thr 24 -uthr 24 -bin $out/masks/csf" >> $out/create_masks_cmds
 
-  ### left hemisphere cortical masks
+  ### left hemisphere cortical masks (from 11101 to 11175)
   for k in {11101..11175}; do
-    kk=`expr $k - 11100`
+    kk=$((k - 11100))
     echo "$FSLDIR/bin/fslmaths $aparc -thr $k -uthr $k -bin $out/masks/left/$kk" >> $out/create_masks_cmds
   done
   #echo "$FSLDIR/bin/fslmaths $aparc -thr 11100 -uthr 12175 -bin $out/cortex" >> $out/create_masks_cmds
-  ### right hemisphere cortical masks
+  ### right hemisphere cortical masks (from 12101 to 12175)
   for k in {12101..12175}; do
-    kk=`expr $k - 12100`
+    kk=$((k - 12100))
     echo "$FSLDIR/bin/fslmaths $aparc -thr $k -uthr $k -bin $out/masks/right/$kk" >> $out/create_masks_cmds
   done
   echo "$FSLDIR/bin/fslmaths $aparc -thr 11100 -uthr 12175 -bin $out/masks/cortex" >> $out/create_masks_cmds
 fi
 
-#$FSLDIR/bin/fslmaths $out/right/cortex -add $out/left/cortex -bin $out/cortex
-
+### warp standard masks into ref space
 for hemi in left right; do
   ### create white matter masks - SCPCT tract
   for tract in scpct_mask{1..15}; do
@@ -224,15 +210,18 @@ for hemi in left right; do
     echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/masks/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
   done
 
+  ### TODO: more masks to be added
+
+  ### warps seeds into ref space
   case "$str" in
     vim)
       ### thalamus - although it's recommend to use FSL's MIST
-      echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/tha -w $warp -o $out/masks/$hemi/tha --interp=nn" >> $out/create_masks_cmds
+      echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/tha -w $warp -o $out/masks/$hemi/seed --interp=nn" >> $out/create_masks_cmds
       echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/vim -w $warp -o $out/masks/$hemi/vim" >> $out/create_masks_cmds
       ;;
     lgn)
       echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/lgn -w $warp -o $out/masks/$hemi/lgn" >> $out/create_masks_cmds
-      echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/lgn_bin -w $warp -o $out/masks/$hemi/lgn_bin  --interp=nn" >> $out/create_masks_cmds
+      echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/lgn_bin -w $warp -o $out/masks/$hemi/seed  --interp=nn" >> $out/create_masks_cmds
       ;;
     *)
       echo "$str currently not supported. "
@@ -242,18 +231,18 @@ for hemi in left right; do
 
   echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/exclusion -w $warp -o $out/masks/$hemi/exclusion --interp=nn" >> $out/create_masks_cmds
 
-  if [ -z "$aparc" ]; then   ### To be removed? maybe not?
-    ### cerebellum - although it's recommend to use freesurfer's segmentation
-    ##### MNI_roi/$hemi/cerebellum_target is the contralateral cerebellar target
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/cerebellum_target -w $warp -o $out/masks/$hemi/cerebellum_target --interp=nn" >> $out/create_masks_cmds
-    ##### MNI_roi/$hemi/cerebellum is ipsilateral cerebellum to avoid
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/cerebellum -w $warp -o $out/masks/$hemi/cerebellum --interp=nn" >> $out/create_masks_cmds
-    ### cortical parcels - if no aparc.a2009s+aseg file is provided
-    for k in {1..75}; do
-      echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$k -w $warp -o $out/masks/$hemi/$k --interp=nn" >> $out/create_masks_cmds
-    done
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/cortex -w $warp -o $out/masks/cortex --interp=nn" >> $out/create_masks_cmds
-  fi
+  # if [ -z "$aparc" ]; then   ### To be removed? maybe not?
+  #   ### cerebellum - although it's recommend to use freesurfer's segmentation
+  #   ##### MNI_roi/$hemi/cerebellum_target is the contralateral cerebellar target
+  #   echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/cerebellum_target -w $warp -o $out/masks/$hemi/cerebellum_target --interp=nn" >> $out/create_masks_cmds
+  #   ##### MNI_roi/$hemi/cerebellum is ipsilateral cerebellum to avoid
+  #   echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/cerebellum -w $warp -o $out/masks/$hemi/cerebellum --interp=nn" >> $out/create_masks_cmds
+  #   ### cortical parcels - if no aparc.a2009s+aseg file is provided
+  #   for k in {1..75}; do
+  #     echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$k -w $warp -o $out/masks/$hemi/$k --interp=nn" >> $out/create_masks_cmds
+  #   done
+  #   echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/cortex -w $warp -o $out/masks/cortex --interp=nn" >> $out/create_masks_cmds
+  # fi
 done
 
 # SCPCT-related ROIs
@@ -288,6 +277,6 @@ if [[ "$queue" == "Yes" ]]; then
     fsl_sub -N create_masks_scpct -n -l $out/logs -j $jobid "bash $out/create_masks_scpct_cmds"
   fi
 else
-  bash "$out/create_masks_cmds"
-  bash "$out/create_masks_scpct_cmds"
+  cat "$out/create_masks_cmds"
+  cat "$out/create_masks_scpct_cmds"
 fi
