refactor create_masks

diff --git a/scripts/create_masks b/scripts/create_masks
--- a/scripts/create_masks
+++ b/scripts/create_masks
@@ -1,29 +1,34 @@
 #!/bin/bash
 
+#   Copyright (C) 2019 University of Oxford
+#
+#   SHCOPYRIGHT
+
+# Written by Ying-Qiu Zheng
+
 Usage() {
     echo ""
-    echo "Usage: create_masks --ref=subj001/t1.nii.gz --warp=subj001/standard2str.nii.gz --out=subj001/roi --aparc=subj001/aparc.a2009s+aseg.nii.gz"
-    echo "       or with short flags:"
-    echo "       create_masks -r subj001/t1.nii.gz -w subj001/standard2str.nii.gz -o subj001/roi -a subj001/aparc.a2009s+aseg.nii.gz"
+    echo "Usage: create_masks [-ref <path>] [-warp <path>] [-out <folder>] [-aparc <path>] [-brainmask <path>]"
+    echo ""
+    echo "Example usage: create_masks -ref subj001/t1.nii.gz -out subj001 -aparc subj001/aparc.a2009s+aseg.nii.gz -warp subj001/std2str_warp.nii.gz"
     echo ""
     echo "Description:"
-    echo "  Creates anatomical masks in reference space (--ref) for tractography and stores them in the output directory (--out)."
+    echo "  Creates anatomical masks in reference space (-ref) for tractography and stores them under the output folder."
     echo ""
     echo "Options:"
-    echo "  -r, --ref         The reference image, typically in the individual T1 native space."
-    echo "  -w, --warp        The warp field mapping the MNI standard space to individual T1 space."
-    echo "  -a, --aparc       Cortical segmentation file from Freesurfer (in *.mgz, *.nii.gz, or *.nii formats)."
-    echo "  -o, --out         (Optional) Directory to store the anatomical masks."
-    echo "                               Defaults to a 'roi' folder in the same directory as the reference image."
-    echo "  -b, --brainmask   (Optional) Binary brain mask in the reference space."
-    echo "  -q, --queue       (Optional) Queue for job submissions. Defaults to local execution."
-    echo "  -n, --njobs       (Optional) Number of jobs to run in parallel locally. Defaults to 1."
+    echo "  -ref         Path to reference image, typically in the individual T1 native space or diffusion space."
+    echo "  -warp        Path to warp field mapping the MNI standard space to the reference space."
+    echo "  -aparc       Path to cortical segmentation file generated by Freesurfer. Must be inthe reference space."
+    echo "  -out         Path to output folder."
+    echo "  -brainmask   (Optional) Path to binary brain mask in the reference space."
+    echo "  -queue       (Optional) Queue for job submissions. Defaults to local execution."
+    echo "  -njobs       (Optional) Number of jobs to run in parallel locally. Defaults to 1."
     echo ""
     exit 1
 }
 
 
-[ "$1" = "" ] && Usage
+[ -z "$1" ] && Usage
 
 if [ -z "$FSLDIR" ]; then
   echo "Environment variable $FSLDIR does not exist. Please set up FSLDIR. "
@@ -52,100 +57,73 @@ get_abs_file_path() {
     echo "$abs_path"
 }
 
-# default njobs
+# set default options
+ref=""
+warp=""
+aparc=""
+out=""
+brainmask=""
+queue="short"
 njobs=1
 
 ### parse arguments
 for arg in "$@"
 do
   case $arg in
-    -h|--help)
+    -help)
     Usage
     ;;
-    -r|--ref)
-      shift
-      ref="$1"
-      shift
-      ;;
-    -o|--out)
-      shift
-      out="$1"
+    -ref)
+      ref="$2"
       shift
       ;;
-    -w|--warp)
-      shift
-      warp="$1"
-      shift
-      ;;
-    -a|--aparc)
-      shift
-      aparc="$1"
+    -out)
+      out="$2"
       shift
       ;;
-    -b|--brainmask)
-      shift
-      brainmask="$1"
-      shift
-      ;;
-    -q|--queue)
-      shift
-      queue="$1"
+    -warp)
+      warp="$2"
       shift
       ;;
-    -n|--njobs)
-      shift
-      njobs="$1"
-      shift
-      ;;
-    --ref=*)
-      ref="${arg#*=}"
+    -aparc)
+      aparc="$2"
       shift
       ;;
-    --out=*)
-      out="${arg#*=}"
+    -brainmask)
+      brainmask="$2"
       shift
       ;;
-    --warp=*)
-      warp="${arg#*=}"
+    -queue)
+      queue="$2"
       shift
       ;;
-    --aparc=*)
-      aparc="${arg#*=}"
-      shift
-      ;;
-    --brainmask=*)
-      brainmask="${arg#*=}"
-      shift
-      ;;
-    --queue=*)
-      queue="${arg#*=}"
-      shift
-      ;;
-    --njobs=*)
-      njobs="${arg#*=}"
+    -njobs)
+      njobs="$2"
       shift
       ;;
     *)
-      # echo "Error: Invalid argument: $arg"
-      # Usage
-      # exit 1
+      echo "Error: Invalid argument: $arg"
+      Usage
+      exit 1
     ;;
   esac
 done
 
 ### Check if required arguments are provided
 if [ -z "$ref" ]; then
-  echo "Error: Missing required argument --ref"
+  echo "Error: Missing required argument -ref. Please specify the reference image."
+  Usage
   exit 1
 elif [ ! -f $ref ]; then
-  echo "Error: $ref not exist"
+  echo "Error: $ref not exist. "
   exit 1
 else
   refpath=$(get_abs_file_path "$ref")
 fi
 
 if [ -z "$warp" ]; then
-  echo "Error: Missing required argument --warp"
+  echo "Error: Missing required argument -warp. Please specify the warp field mapping the MNI standard space to reference space."
+  Usage
   exit 1
 elif [ ! -f $warp ]; then
   echo "Error: $warp not exist"
@@ -153,10 +131,16 @@ elif [ ! -f $warp ]; then
 fi
 
 if [ -z "$aparc" ]; then
-  echo "Error: Missing required argument --aparc"
+  echo "Error: Missing required argument -aparc. Please specify the cortical parcellation file (generated by recon-all)."
   exit 1
 elif [ ! -f $aparc ]; then
   echo "Error: $aparc not exist"
+  exit 1
+fi
+
+if [ -z "$out" ]; then
+  echo "Error: Missing required argument -out. Please specify the output directory."
+  Usage
   exit 1
 fi
 
@@ -170,19 +154,14 @@ if [ ! -z "$queue" ]; then
   fi
 fi
 
-if [ -z "$out" ]; then
-  out=$(dirname $refpath)/roi
-  echo "output directory not specified. create $out to store anatomical masks in reference space"
-fi
-
 ### create output directory
-if [ ! -d $out ]; then
-  mkdir -p $out
+if [ ! -d $out/masks ]; then
+  mkdir -p $out/masks
 fi
 ### create dir for left and right hemisphere
 for hemi in left right; do
-  if [ ! -d $out/$hemi ]; then
-    mkdir $out/$hemi
+  if [ ! -d $out/masks/$hemi ]; then
+    mkdir $out/masks/$hemi
   fi
 done
 
@@ -193,94 +172,91 @@ if [ ! -z "$aparc" ]; then
       echo "If you feed in the aparc.a2009s+aseg in *.mgz format, please set up FREESURFER_HOME. "
       exit 1
     fi
-    $FREESURFER_HOME/bin/mri_convert $aparc $out/${aparc_basename%.*}.nii.gz
-    $FSLDIR/bin/flirt -in $out/${aparc_basename%.*}.nii.gz -ref $ref -out $out/${aparc_basename%.*}.nii.gz -applyxfm -usesqform -interp nearestneighbour
-    aparc="$out/${aparc_basename%.*}.nii.gz"
+    $FREESURFER_HOME/bin/mri_convert $aparc $out/masks/${aparc_basename%.*}.nii.gz
+    $FSLDIR/bin/flirt -in $out/masks/${aparc_basename%.*}.nii.gz -ref $ref -out $out/masks/${aparc_basename%.*}.nii.gz -applyxfm -usesqform -interp nearestneighbour
+    aparc="$out/masks/${aparc_basename%.*}.nii.gz"
   elif [[ "$aparc" == *.nii ]] || [[ "$aparc" == *.nii.gz ]]; then
-    $FSLDIR/bin/flirt -in $aparc -ref $ref -out $out/${aparc_basename%.*}.nii.gz -applyxfm -usesqform -interp nearestneighbour 
-    aparc="$out/${aparc_basename%.*}.nii.gz"
+    $FSLDIR/bin/flirt -in $aparc -ref $ref -out $out/masks/${aparc_basename%.*}.nii.gz -applyxfm -usesqform -interp nearestneighbour 
+    aparc="$out/masks/${aparc_basename%.*}.nii.gz"
   else
     echo "Invalid aparc.a2009s+aseg file. Please use *.mgz or *.nii.gz/*.nii file."
     exit 1
   fi
   #### cerebellum
-  echo "echo Create cerebellar ROIs based on the provided $aparc file..." > $out/create_masks_cmds
-  echo "$FSLDIR/bin/fslmaths $aparc -thr 6 -uthr 8 -bin $out/left/cerebellum" >> $out/create_masks_cmds
-  echo "$FSLDIR/bin/fslmaths $aparc -thr 45 -uthr 47 -bin $out/right/cerebellum" >> $out/create_masks_cmds
-  echo "$FSLDIR/bin/fslmaths $aparc -thr 7 -uthr 7 -bin $out/right/cerebellum_target" >> $out/create_masks_cmds
-  echo "$FSLDIR/bin/fslmaths $aparc -thr 46 -uthr 46 -bin $out/left/cerebellum_target" >> $out/create_masks_cmds
-  echo "$FSLDIR/bin/fslmaths $aparc -thr 24 -uthr 24 -bin $out/csf" >> $out/create_masks_cmds
+  echo "$FSLDIR/bin/fslmaths $aparc -thr 6 -uthr 8 -bin $out/masks/left/cerebellum" > $out/create_masks_cmds
+  echo "$FSLDIR/bin/fslmaths $aparc -thr 45 -uthr 47 -bin $out/masks/right/cerebellum" >> $out/create_masks_cmds
+  echo "$FSLDIR/bin/fslmaths $aparc -thr 7 -uthr 7 -bin $out/masks/right/cerebellum_target" >> $out/create_masks_cmds
+  echo "$FSLDIR/bin/fslmaths $aparc -thr 46 -uthr 46 -bin $out/masks/left/cerebellum_target" >> $out/create_masks_cmds
+  echo "$FSLDIR/bin/fslmaths $aparc -thr 24 -uthr 24 -bin $out/masks/csf" >> $out/create_masks_cmds
+
   ### left hemisphere cortical masks
-  echo "echo Create left hemisphere cortical ROIs based on the provided $aparc file..." >> $out/create_masks_cmds
   for k in {11101..11175}; do
     kk=`expr $k - 11100`
-    echo "$FSLDIR/bin/fslmaths $aparc -thr $k -uthr $k -bin $out/left/$kk" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/fslmaths $aparc -thr $k -uthr $k -bin $out/masks/left/$kk" >> $out/create_masks_cmds
   done
   #echo "$FSLDIR/bin/fslmaths $aparc -thr 11100 -uthr 12175 -bin $out/cortex" >> $out/create_masks_cmds
   ### right hemisphere cortical masks
-  echo "echo Create right hemisphere cortical ROIs based on the provided $aparc file..." >> $out/create_masks_cmds
   for k in {12101..12175}; do
     kk=`expr $k - 12100`
-    echo "$FSLDIR/bin/fslmaths $aparc -thr $k -uthr $k -bin $out/right/$kk" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/fslmaths $aparc -thr $k -uthr $k -bin $out/masks/right/$kk" >> $out/create_masks_cmds
   done
-  echo "$FSLDIR/bin/fslmaths $aparc -thr 11100 -uthr 12175 -bin $out/cortex" >> $out/create_masks_cmds
+  echo "$FSLDIR/bin/fslmaths $aparc -thr 11100 -uthr 12175 -bin $out/masks/cortex" >> $out/create_masks_cmds
 fi
 
 #$FSLDIR/bin/fslmaths $out/right/cortex -add $out/left/cortex -bin $out/cortex
 
 for hemi in left right; do
-  echo "echo Create masks for $hemi hemisphere..." >> $out/create_masks_cmds
   ### create white matter masks - SCPCT tract
   for tract in scpct_mask{1..15}; do
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/masks/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
   done
   ### STR
   for tract in str_mask{1..10}; do
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/masks/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
   done
   ### ATR
   for tract in atr_mask{1..8}; do
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/masks/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
   done
   ### AR
   for tract in ar_mask{1..8}; do
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/masks/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
   done
   ### OR
   for tract in or_mask{1..10}; do
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/masks/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
   done
   ### fornix
   for tract in fx_mask{1..10}; do
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/masks/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
   done
   ### M1
   for tract in to_precentral_mask{1..12}; do
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/masks/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
   done
   ### S1
   for tract in to_postcentral_mask{1..12}; do
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$tract -w $warp -o $out/masks/$hemi/$tract --interp=nn" >> $out/create_masks_cmds
   done
 
   ### thalamus - although it's recommend to use FSL's MIST
-  echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/tha -w $warp -o $out/$hemi/tha --interp=nn" >> $out/create_masks_cmds
+  echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/tha -w $warp -o $out/masks/$hemi/tha --interp=nn" >> $out/create_masks_cmds
 
-  echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/vim -w $warp -o $out/$hemi/vim" >> $out/create_masks_cmds
+  echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/vim -w $warp -o $out/masks/$hemi/vim" >> $out/create_masks_cmds
 
-  echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/exclusion -w $warp -o $out/$hemi/exclusion --interp=nn" >> $out/create_masks_cmds
+  echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/exclusion -w $warp -o $out/masks/$hemi/exclusion --interp=nn" >> $out/create_masks_cmds
 
-  if [ -z "$aparc" ]; then
+  if [ -z "$aparc" ]; then   ### To be removed
     ### cerebellum - although it's recommend to use freesurfer's segmentation
     ##### MNI_roi/$hemi/cerebellum_target is the contralateral cerebellar target
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/cerebellum_target -w $warp -o $out/$hemi/cerebellum_target --interp=nn" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/cerebellum_target -w $warp -o $out/masks/$hemi/cerebellum_target --interp=nn" >> $out/create_masks_cmds
     ##### MNI_roi/$hemi/cerebellum is ipsilateral cerebellum to avoid
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/cerebellum -w $warp -o $out/$hemi/cerebellum --interp=nn" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/cerebellum -w $warp -o $out/masks/$hemi/cerebellum --interp=nn" >> $out/create_masks_cmds
     ### cortical parcels - if no aparc.a2009s+aseg file is provided
     for k in {1..75}; do
-      echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$k -w $warp -o $out/$hemi/$k --interp=nn" >> $out/create_masks_cmds
+      echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/$k -w $warp -o $out/masks/$hemi/$k --interp=nn" >> $out/create_masks_cmds
     done
-    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/cortex -w $warp -o $out/$hemi/cortex --interp=nn" >> $out/create_masks_cmds
+    echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/cortex -w $warp -o $out/masks/cortex --interp=nn" >> $out/create_masks_cmds
   fi
 done
 
@@ -290,35 +266,22 @@ echo "echo Create SCPCT-related ROIs..." > $out/create_masks_scpct_cmds
 ### if brain mask not provided, use standard
 if [ -z "$brainmask" ]; then
   #echo "echo brainmask not provided. use standard brain mask MNI152_T1_1mm_brain_mask instead..." >> $out/create_masks_scpct_cmds
-  echo "$FSLDIR/bin/applywarp -r $ref -i $FSLDIR/data/standard/MNI152_T1_1mm_brain_mask -w $warp -o $out/brain_mask --interp=nn" >> $out/create_masks_scpct_cmds
-  brainmask="$out/brain_mask"
+  echo "$FSLDIR/bin/applywarp -r $ref -i $FSLDIR/data/standard/MNI152_T1_1mm_brain_mask -w $warp -o $out/masks/brain_mask --interp=nn" >> $out/create_masks_scpct_cmds
+  brainmask="$out/masks/brain_mask"
 fi
 
 for hemi in left right; do
   ### SCPCT
-  echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/SCPCT -w $warp -o $out/$hemi/SCPCT" >> $out/create_masks_scpct_cmds
-  echo "$FSLDIR/bin/fslmaths $out/$hemi/SCPCT -thr 0.0001 -bin $out/$hemi/SCPCT_bin" >> $out/create_masks_scpct_cmds
+  echo "$FSLDIR/bin/applywarp -r $ref -i $RESOURCES_DIR/MNI_roi/$hemi/SCPCT -w $warp -o $out/masks/$hemi/SCPCT" >> $out/create_masks_scpct_cmds
+  echo "$FSLDIR/bin/fslmaths $out/masks/$hemi/SCPCT -thr 0.0001 -bin $out/masks/$hemi/SCPCT_bin" >> $out/create_masks_scpct_cmds
   ### if brain mask not provided, use standard
   #if [ -z "$brainmask" ]; then
     #echo "$FSLDIR/bin/fslmaths $out/brain_mask -rem $out/$hemi/SCPCT_bin -bin -rem $out/$hemi/tha -bin $out/$hemi/stop_for_scpct" >> $out/create_masks_scpct_cmds
   #else
-  echo "$FSLDIR/bin/fslmaths $brainmask -rem $out/$hemi/SCPCT_bin -bin -rem $out/$hemi/tha -bin $out/$hemi/stop_for_scpct" >> $out/create_masks_scpct_cmds
+  echo "$FSLDIR/bin/fslmaths $brainmask -rem $out/masks/$hemi/SCPCT_bin -bin -rem $out/masks/$hemi/tha -bin $out/masks/$hemi/stop_for_scpct" >> $out/create_masks_scpct_cmds
   #fi
 done
 
-# execute locally or submit the jobs...
-if [ -z "$queue" ]; then
-  if [[ $njobs -eq 1 ]]; then
-    bash "$out/create_masks_cmds"
-  else
-    "$SCRIPT_DIR/run_parallel" "$out/create_masks_cmds" $njobs
-  fi
-  bash "$out/create_masks_scpct_cmds"
-else
-  if [ ! -d $out/log ]; then
-    mkdir $out/logs
-  fi;
-  fsl_sub -q $queue -N create_masks -l $out/logs -t "$out/create_masks_cmds"
-  fsl_sub -q $queue -N create_masks_scpct -l $out/logs "bash $out/create_masks_scpct_cmds"
-  echo "jobs submitted. Logs will be stored under $out/logs."
-fi
+fsl_sub -N create_masks -l $out/logs -t "$out/create_masks_cmds"
+fsl_sub -N create_masks_scpct -l $out/logs "bash $out/create_masks_scpct_cmds"
+echo "jobs submitted. Logs will be stored under $out/logs. Masks will be stored under $out/masks."
